### ISSUE TITLE
review dplyr training for 4.27.20

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/coRps#1]
Gentlemen, I could use a little help reviewing what I had in mind for `dplyr`. My idea was to focus on four functions: `select`, `rename`, `filter`, and `mutate`, in that order. Along the way, I want to introduce the `_if`, `_at`, and `_all` variants, but `_at` may be too much. I also want to introduce the "helpers": ranges, `contains`, `is.numeric`, boolean, etc.. 

If you can help me think about how to organize all of that I can add to what is here. Also any thoughts around the structure, this is my first time trying to work through an instructional thing in .rmd

I'm working off a branch [here](https://github.com/USAID-OHA-SI/coRps/tree/josh/2020-04-27)

**Comment by achafetz** [comment]
@jaliasd  what dataset are you using? this looks like its attempting to use the whole MilkyWay dataset. We want a watered down version when getting them going so they can wrap their head around 10 instead of 35 columns. And filtering it down would be good too. No need for all the lab indicators, etc

I think you need to address the url link. Its not pointing to the dataset.
https://github.com/USAID-OHA-SI/coRps/blob/dc9d3eaf889c6300dc293f4857aed306fd9d5c68/2020-04-27/transform_data.Rmd#L25-L27

maybe for rename, also showing how you can do the same thing with select (but the trade off is limiting the columns or having to write out each column).

maybe instead of going too indepth with the select statements, getting to filter first and mutate. Here, the logicals and select statements can be even more powerful (ie for filter you need == and !+ and %in% and using start_with or other select statements is great with mutate_at)
